import { ThemeProvider } from '@/providers/theme-provider';
import type { Metadata } from 'next';
import { Gelasio, Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';

const fontSans = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
});

const fontSerif = Gelasio({
	subsets: ['latin'],
	variable: '--font-serif',
});

const fontMono = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
